urllogin.settings:
  type: mapping
  label: Variable Settings of urllogin
  mapping:
    passphrase:
      type: string
    add_dbpass:
      type: boolean
    codekey:
      type: integer
    codemin:
      type: integer
    destination:
      type: string
    useprofile:
      type: boolean
